package prog3360.assignment1_order_service;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import prog3360.assignment1_order_service.domain.entity.Order;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit test class for Order Service, auto-generated by Spring Boot.
 * Uses JUnit 5 framework for testing.
 * Can run via: (1) Maven 'mvn test' or 'mvn package', (2) IDE test runner.
 * In this project: Runs via 'mvn -B test' in GitHub Actions CI/CD and 'RUN mvn clean package' in Dockerfile.
 * @SpringBootTest loads full application context for integration-style testing.
 */
@SpringBootTest
class Assignment1OrderServiceApplicationTests {

	/**
	 * Default test that comes with Spring Boot initialization.
	 * Why: Verify Spring application context loads successfully.
	 * How: Spring automatically runs this to ensure all beans and configurations are valid.
	 */
	@Test
	void contextLoads() {
	}

	/**
	 * Test constructor with productId and quantity.
	 * Why: Ensure Order entity can be instantiated with required fields.
	 * How: Create Order with Long productId and int quantity, then verify.
	 */
	@Test
	void testOrderCreation() {
		Order order = new Order(1L, 3);

		assertEquals(1L, order.getProductId());
		assertEquals(3, order.getQuantity());
	}

	/**
	 * Test setter methods including totalPrice and status.
	 * Why: Validate that Order setters work correctly for all fields.
	 * How: Create empty Order, set all values via setters, then verify.
	 */
	@Test
	void testOrderSetters() {
		Order order = new Order();
		order.setProductId(2L);
		order.setQuantity(2);
		order.setTotalPrice(2026.02);
		order.setStatus("PENDING");

		assertEquals(2L, order.getProductId());
		assertEquals(2, order.getQuantity());
		assertEquals(2026.02, order.getTotalPrice());
		assertEquals("PENDING", order.getStatus());
	}

}