package prog3360.assignment1_product_service;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import prog3360.assignment1_product_service.domain.entity.Product;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit test class for Product Service, auto-generated by Spring Boot.
 * Uses JUnit 5 framework for testing.
 * Can run via: (1) Maven 'mvn test' or 'mvn package', (2) IDE test runner.
 * In this project: Runs via 'mvn -B test' in GitHub Actions CI/CD and 'RUN mvn clean package' in Dockerfile.
 * @SpringBootTest loads full application context for integration-style testing.
 */
@SpringBootTest
class Assignment1ProductServiceApplicationTests {

	/**
	 * Default test that comes with Spring Boot initialization.
	 * Why: Verify Spring application context loads successfully.
	 * How: Spring automatically runs this to ensure all beans and configurations are valid.
	 */
	@Test
	void contextLoads() {
	}

	/**
	 * Test constructor with parameters.
	 * Why: Ensure Product entity can be instantiated with valid data.
	 * How: Create Product with name, price, quantity and verify all fields.
	 */
	@Test
	void testProductCreation() {
		Product product = new Product("Juhwan's Laptop", 1996.01, 15);

		assertEquals("Juhwan's Laptop", product.getName());
		assertEquals(1996.01, product.getPrice());
		assertEquals(15, product.getQuantity());
	}

	/**
	 * Test setter methods for all Product fields.
	 * Why: Validate that Product setters work correctly.
	 * How: Create empty Product, set values via setters, then verify.
	 */
	@Test
	void testProductSetters() {
		Product product = new Product();
		product.setName("Nathan's Macbook");
		product.setPrice(2003.08);
		product.setQuantity(8);

		assertEquals("Nathan's Macbook", product.getName());
		assertEquals(2003.08, product.getPrice());
		assertEquals(8, product.getQuantity());
	}

}
